// ============================================================
// Reports Page
// ============================================================

import { useState } from 'react';
import { motion } from 'framer-motion';
import { HiOutlineMagnifyingGlass, HiOutlineDocumentArrowDown, HiOutlineChevronLeft, HiOutlineChevronRight } from 'react-icons/hi2';

const mockReports = [
  { id: '1', name: 'Daily Participants Report', type: 'participants' as const, format: 'pdf' as const, generatedAt: new Date().toISOString(), generatedBy: 'Admin' },
  { id: '2', name: 'Weekly Draw Summary', type: 'draws' as const, format: 'csv' as const, generatedAt: new Date(Date.now() - 86400000).toISOString(), generatedBy: 'System' },
  { id: '3', name: 'Winner List - July', type: 'winners' as const, format: 'excel' as const, generatedAt: new Date(Date.now() - 172800000).toISOString(), generatedBy: 'Admin' },
  { id: '4', name: 'Prize Inventory', type: 'prizes' as const, format: 'pdf' as const, generatedAt: new Date(Date.now() - 259200000).toISOString(), generatedBy: 'Admin' },
  { id: '5', name: 'Queue Performance', type: 'queue' as const, format: 'csv' as const, generatedAt: new Date(Date.now() - 345600000).toISOString(), generatedBy: 'System' },
];

const typeColors: Record<string, string> = {
  participants: 'bg-primary-500/20 text-primary-400',
  draws: 'bg-secondary-500/20 text-secondary-400',
  winners: 'bg-success-500/20 text-success-400',
  prizes: 'bg-warning-500/20 text-warning-400',
  queue: 'bg-accent-500/20 text-accent-400',
};

const formatIcons: Record<string, string> = {
  pdf: '📄',
  csv: '📊',
  excel: '📗',
};

export default function ReportsPage() {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const pageSize = 10;

  const filtered = mockReports.filter((r) => r.name.toLowerCase().includes(search.toLowerCase()));
  const totalPages = Math.ceil(filtered.length / pageSize);
  const paginated = filtered.slice((page - 1) * pageSize, page * pageSize);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Reports</h1>
          <p className="text-sm text-dark-text-tertiary mt-1">{filtered.length} generated reports</p>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary-500/10 text-primary-400 hover:bg-primary-500/20 transition-colors text-sm">
          <HiOutlineDocumentArrowDown className="w-4 h-4" />
          Generate Report
        </button>
      </div>

      <div className="relative max-w-md">
        <HiOutlineMagnifyingGlass className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-dark-text-tertiary" />
        <input type="text" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}
          placeholder="Search reports..." className="w-full pl-10 pr-4 py-2 rounded-lg bg-dark-surface-secondary border border-dark-border text-white placeholder-dark-text-tertiary outline-none focus:border-primary-500/50 transition-colors text-sm" />
      </div>

      <div className="rounded-xl border border-dark-border bg-dark-surface-secondary overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-dark-border">
                <th className="text-left px-4 py-3 text-xs font-medium text-dark-text-tertiary uppercase tracking-wider">Name</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-dark-text-tertiary uppercase tracking-wider">Type</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-dark-text-tertiary uppercase tracking-wider">Format</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-dark-text-tertiary uppercase tracking-wider">Generated By</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-dark-text-tertiary uppercase tracking-wider">Date</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-dark-text-tertiary uppercase tracking-wider">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-dark-border/50">
              {paginated.map((r, i) => (
                <motion.tr key={r.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}
                  className="hover:bg-dark-surface-tertiary/50 transition-colors">
                  <td className="px-4 py-3 text-sm text-white font-medium">{r.name}</td>
                  <td className="px-4 py-3">
                    <span className={`px-2 py-0.5 text-xs font-medium rounded-full ${typeColors[r.type]}`}>{r.type}</span>
                  </td>
                  <td className="px-4 py-3 text-sm text-dark-text-secondary">{formatIcons[r.format]} {r.format.toUpperCase()}</td>
                  <td className="px-4 py-3 text-sm text-dark-text-secondary">{r.generatedBy}</td>
                  <td className="px-4 py-3 text-sm text-dark-text-tertiary">{new Date(r.generatedAt).toLocaleDateString()}</td>
                  <td className="px-4 py-3 text-right">
                    <button className="px-3 py-1.5 rounded-lg bg-primary-500/10 text-primary-400 hover:bg-primary-500/20 transition-colors text-xs font-medium">
                      Download
                    </button>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="flex items-center justify-between px-4 py-3 border-t border-dark-border">
          <p className="text-sm text-dark-text-tertiary">Page {page} of {totalPages}</p>
          <div className="flex items-center gap-2">
            <button onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1}
              className="p-1.5 rounded-lg text-dark-text-tertiary hover:text-white hover:bg-dark-surface-tertiary disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
              <HiOutlineChevronLeft className="w-4 h-4" />
            </button>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
              <button key={p} onClick={() => setPage(p)}
                className={`w-8 h-8 rounded-lg text-sm transition-colors ${p === page ? 'bg-primary-500/20 text-primary-400' : 'text-dark-text-tertiary hover:text-white hover:bg-dark-surface-tertiary'}`}>
                {p}
              </button>
            ))}
            <button onClick={() => setPage(Math.min(totalPages, page + 1))} disabled={page === totalPages}
              className="p-1.5 rounded-lg text-dark-text-tertiary hover:text-white hover:bg-dark-surface-tertiary disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
              <HiOutlineChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
