/**
 * Queue Store (Backend-Synced Cache)
 *
 * This store is a read-only cache of the backend queue state.
 * It is kept in sync via:
 *   1. Initial fetch from GET /queue/state
 *   2. Real-time updates from Socket.IO queue events
 *      (queue:created, queue:updated, queue:called, queue:completed,
 *       queue:skipped, queue:cancelled)
 *
 * Queue numbers are ALWAYS generated by the backend. This store never
 * generates queue numbers locally.
 */

import { create } from 'zustand';
import { queueApi, type QueueState } from '../../api/queue';
import { registerParticipant } from '../../features/registration/api';

export type QueueStatus = 'waiting' | 'current' | 'finished' | 'cancelled' | 'skipped';

export interface QueueItem {
  id: string;
  number: string; // e.g. "A001"
  fullName: string;
  phone: string;
  company: string;
  email: string;
  status: QueueStatus;
  isPriority: boolean;
  registeredAt: number;
  startedAt?: number;
  finishedAt?: number;
  estimatedDuration: number; // minutes
}

interface QueueStateShape {
  // Queue data (cache)
  items: QueueItem[];
  currentIndex: number;
  prefix: string;
  counter: number;
  estimatedWaitPerItem: number; // minutes
  estimatedWait: number; // minutes (from backend)
  totalWaiting: number;
  totalFinished: number;
  totalCancelled: number;
  lastCalled?: string;
  isSynced: boolean;
  isSyncing: boolean;
  syncError: string | null;

  // Computed
  currentQueue: QueueItem | null;
  waitingQueue: QueueItem[];
  finishedQueue: QueueItem[];
  cancelledQueue: QueueItem[];

  // Actions
  syncState: (state: QueueState) => void;
  fetchState: () => Promise<void>;
  addParticipant: (data: {
    fullName: string;
    phone: string;
    company: string;
    email: string;
  }) => Promise<string>;
  addPriority: (data: {
    fullName: string;
    phone: string;
    company: string;
    email: string;
  }) => Promise<string>;
  nextQueue: () => Promise<void>;
  cancelQueue: (id: string) => Promise<void>;
  skipQueue: (id: string) => Promise<void>;
  finishCurrent: () => Promise<void>;
  resetQueue: () => void;
  setEstimatedWait: (minutes: number) => void;
  setPrefix: (prefix: string) => void;
  getEstimatedWait: (position?: number) => number;
  getQueueByNumber: (number: string) => QueueItem | undefined;
}

/** Map a backend queue entry to the client QueueItem shape */
function mapEntry(entry: {
  id: string;
  participantId: string;
  participantName: string;
  queueNumber: string;
  status: string;
  createdAt: string;
}): QueueItem {
  const status = normalizeStatus(entry.status);
  return {
    id: entry.id,
    number: entry.queueNumber,
    fullName: entry.participantName,
    phone: '',
    company: '',
    email: '',
    status,
    isPriority: false,
    registeredAt: new Date(entry.createdAt).getTime(),
    estimatedDuration: 0,
  };
}

function normalizeStatus(status: string): QueueStatus {
  switch (status) {
    case 'called':
      return 'current';
    case 'completed':
      return 'finished';
    case 'cancelled':
      return 'cancelled';
    case 'skipped':
      return 'skipped';
    default:
      return 'waiting';
  }
}

export const useQueueStore = create<QueueStateShape>((set, get) => ({
  items: [],
  currentIndex: -1,
  prefix: 'A',
  counter: 1,
  estimatedWaitPerItem: 3,
  estimatedWait: 0,
  totalWaiting: 0,
  totalFinished: 0,
  totalCancelled: 0,
  isSynced: false,
  isSyncing: false,
  syncError: null,

  // Computed getters
  get currentQueue() {
    const { items, currentIndex } = get();
    if (currentIndex < 0 || currentIndex >= items.length) return null;
    return items[currentIndex]?.status === 'current' ? items[currentIndex] : null;
  },

  get waitingQueue() {
    return get().items.filter((item) => item.status === 'waiting');
  },

  get finishedQueue() {
    return get().items.filter((item) => item.status === 'finished');
  },

  get cancelledQueue() {
    return get().items.filter((item) => item.status === 'cancelled' || item.status === 'skipped');
  },

  /** Replace the cache with the authoritative backend state */
  syncState: (state) => {
    const items = state.entries.map(mapEntry);
    const currentIndex = items.findIndex((item) => item.status === 'current');

    set({
      items,
      currentIndex,
      estimatedWait: state.estimatedWait,
      totalWaiting: state.totalWaiting,
      totalFinished: items.filter((i) => i.status === 'finished').length,
      totalCancelled: items.filter((i) => i.status === 'cancelled' || i.status === 'skipped')
        .length,
      lastCalled: state.lastCalled,
      isSynced: true,
      isSyncing: false,
      syncError: null,
    });
  },

  /** Fetch the initial queue state from the backend */
  fetchState: async () => {
    set({ isSyncing: true, syncError: null });
    try {
      const response = await queueApi.getState();
      get().syncState(response.data);
    } catch (error) {
      set({
        isSyncing: false,
        syncError: error instanceof Error ? error.message : 'Failed to load queue',
      });
    }
  },

  /** Register a participant via the backend, then add them to the queue */
  addParticipant: async (data) => {
    const participant = await registerParticipant({
      name: data.fullName,
      phone: data.phone,
      company: data.company,
      email: data.email || undefined,
    });
    await queueApi.addToQueue(participant.id);
    // The queue entry will arrive via socket broadcast; refresh to be safe.
    await get().fetchState();
    return participant.queueNumber;
  },

  addPriority: async (data) => {
    // Backend queue does not currently support priority insertion.
    // Register the participant and add to the queue normally.
    return get().addParticipant(data);
  },

  nextQueue: async () => {
    await queueApi.callNext();
    // State update arrives via socket broadcast.
  },

  cancelQueue: async (id) => {
    const item = get().items.find((i) => i.id === id);
    if (!item) return;
    await queueApi.cancel(item.id);
  },

  skipQueue: async (id) => {
    const item = get().items.find((i) => i.id === id);
    if (!item) return;
    await queueApi.skip(item.id);
  },

  finishCurrent: async () => {
    const current = get().currentQueue;
    if (!current) return;
    await queueApi.completeCurrent(current.id);
  },

  resetQueue: () => {
    // Local UI reset only; the authoritative state is on the backend.
    set({
      items: [],
      currentIndex: -1,
      counter: 1,
      isSynced: false,
    });
  },

  setEstimatedWait: (minutes) => {
    set({ estimatedWaitPerItem: minutes });
  },

  setPrefix: (prefix) => {
    set({ prefix });
  },

  getEstimatedWait: (position) => {
    const state = get();
    const pos = position ?? state.totalWaiting;
    return pos * state.estimatedWaitPerItem;
  },

  getQueueByNumber: (number) => {
    return get().items.find((item) => item.number === number);
  },
}));
